#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart' || return 1
    echo "upstart" found
    return 0
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount' || return 1
    echo "systemd found"
    return 0
}

if [ "$1" = "purge" ] ; then
    if [ -e /etc/stream-schedule/stream-schedule.conf ]; then
        rm /etc/stream-schedule/stream-schedule.conf
    fi
    
    if [ -e /etc/init/stream-schedule.conf ]; then
        rm /etc/init/stream-schedule.conf
    fi
fi

exit 0;
