#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if [ "$1" = "purge" ] ; then
    if [ -e /etc/stream-schedule/stream-schedule.conf ]; then
        rm /etc/stream-schedule/stream-schedule.conf
    fi
    
    if [ -e /etc/init/stream-schedule.conf ]; then
        rm /etc/init/stream-schedule.conf
    fi
fi

if isSystemd; then
	echo "reload systemd services"
	systemctl daemon-reload
fi

exit 0;
