#! /bin/sh -e

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if [ "$1" = "remove" ]; then
	if isUpstart; then
		echo "stop stream-schedule upstart service"
		status stream-schedule && stop stream-schedule || echo "could not stop service"
		initctl reload-configuration
    elif isSystemd; then
		echo "stop stream-schedule systemd service"
		systemctl stop stream-schedule
		systemctl disable stream-schedule
	fi
fi

exit 0
#DEBHELPER#

